name: Test
on:
  push:
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
    - name: Convert CSV Test
      shell: bash -el {0}
      run: |
        conda env create -f environment.yaml
        conda init bash
        conda activate data_visualisation
 
        python convertcsv_test.py
    - name: PCA Plot Test
      shell: bash -el {0}
      run: |
        conda env create -f environment.yaml
        conda init bash
        conda activate data_visualisation
 
        python pcaplot_test.py
 